import "./globals.css";
import { Toaster } from "@/components/ui/sonner";

export const metadata = {
  title: "The White Rooms",
  // description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
      // className={`${centuryGothic.variable} antialiased`}
      >
        <Toaster />
        <main>{children}</main>
      </body>
    </html>
  );
}
